service: reto-backend-serveless

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  profile: aws-deploy
  region: us-east-1
  runtime: nodejs12.x
  environment: '${file(.env.yml):${self:custom.stage}}'
  stage: development
  
  

custom:
  webpack:
    webpackConfig: './webpack.config.${self:custom.stage}.js'
    includeModules:
      forceInclude:
        - sequelize
        - tedious
  stage: ${opt:stage, self:provider.stage}
  serverless-offline:
    httpPort: 3000
    babelOptions:
      presets:
        - env

package:
  exclude:
    - .vscode/**
    - docs/**
    - test/**
    - .editorconfig
    - .env.yml.example
    - .jsbeautifyrc
    - .git/**
    - .gitignore
    - artifacts
    - jsdoc.conf
    - jsdoc.conf.json
    - README.md

functions:
  films:
    description: Film resource list and creation.
    handler: functions/films.handler
    events:
      - http:
          path: api/films
          method: get 
          cors: true
          request:
            parameters:
              querystrings:
                lang: true
      - http: 
          path: api/films
          method: post 
          cors: true
      - http:
          path: api/films/{id}
          method: get 
          cors: true
          request:
            parameters:
              paths:
                id: true
      - http:
          path: api/films/{id}
          method: patch
          cors: true
          request:
            parameters:
              paths:
                id: true
      - http:
          path: api/films/{id}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                id: true

  people:
    description: A People resource is an individual person or character within the Star Wars universe.
    handler: functions/people.handler
    events:
      - http:
          path: api/people
          method: get 
          cors: true
          request:
            parameters:
              querystrings:
                lang: true
      - http: 
          path: api/people
          method: post 
          cors: true
      - http:
          path: api/people/{id}
          method: get 
          cors: true
          request:
            parameters:
              paths:
                id: true
      - http:
          path: api/people/{id}
          method: patch
          cors: true
          request:
            parameters:
              paths:
                id: true
      - http:
          path: api/people/{id}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                id: true
         